[build]
  command = "npm run build"
  publish = "out" # or .next, dist, etc., depending on your framework

# Optional redirects, headers, etc., can stay here
# [[redirects]]
#   from = "/old"
#   to = "/new"
#   status = 301
